@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyContactBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class ContactBook
Class ReadOnlyContactBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniquePersonList
Class Person
Class Detail
Class Email
Class Github
Class LinkedIn
Class Name
Class Phone
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ContactBook .up.|> ReadOnlyContactBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyContactBook
ModelManager -left-> "1" ContactBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ContactBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" Github
Person *--> "1" LinkedIn
Person *--> "*" Tag
Person *--> "1" Detail

Name -[hidden]right-> Phone
Email -[hidden]right-> Tag
Github -[hidden]right-> Tag
LinkedIn -[hidden]right-> Tag
Tag -[hidden]right-> Detail

ModelManager -->"~* filtered" Person
@enduml
