@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniquePersonList
Class Person
Class Detail
Class Email
Class Github
Class LinkedIn
Class Name
Class Phone
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person
Person *--> Name
Person *--> "*" Phone
Person *--> "*" Email
Person *--> "*" Github
Person *--> "*" LinkedIn
Person *--> "*" Tag
Person *--> "*" Detail

Name -[hidden]right-> Phone
Email -[hidden]right-> Tag
Github -[hidden]right-> Tag
LinkedIn -[hidden]right-> Tag
Tag -[hidden]right-> Detail

ModelManager -->"~* filtered" Person
@enduml
