@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "ContactBook Storage" #F4F6F6{
Interface ContactBookStorage <<Interface>>
Class JsonContactBookStorage
Class JsonSerializableContactBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ContactBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ContactBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonContactBookStorage .up.|> ContactBookStorage
JsonContactBookStorage ..> JsonSerializableContactBook
JsonSerializableContactBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
